name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@bd65736f7e9658e5a887ebe9bf855cf690b9d596
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml
