name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@3c64c1f94e07de94590cb9cb3b91bf954a986618
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
