name: Global workflow to rule all other worklowsa

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@052a1a2252ee26c964e18ea88ca89989e6344bc2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
